/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadResumeRouteImport } from './routes/uploadResume'
import { Route as SkillGapRouteImport } from './routes/skillGap'
import { Route as ResumeReportRouteImport } from './routes/resumeReport'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParsedResumeRouteImport } from './routes/parsedResume'
import { Route as MyResumesRouteImport } from './routes/myResumes'
import { Route as LearningPlanRouteImport } from './routes/learningPlan'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as JobDetailsRouteImport } from './routes/jobDetails'
import { Route as JobDetailWithSkillGapRouteImport } from './routes/jobDetailWithSkillGap'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountSettingRouteImport } from './routes/accountSetting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySupportRouteImport } from './routes/company/support'
import { Route as CompanySettingsRouteImport } from './routes/company/settings'
import { Route as CompanyProfileSetupRouteImport } from './routes/company/profileSetup'
import { Route as CompanyJobsRouteImport } from './routes/company/jobs'
import { Route as CompanyDashboardRouteImport } from './routes/company/dashboard'
import { Route as CompanyCandidatesRouteImport } from './routes/company/candidates'
import { Route as CompanyCandidateDetailRouteImport } from './routes/company/candidateDetail'
import { Route as CompanyCadidateMatchRouteImport } from './routes/company/cadidateMatch'
import { Route as CompanyAddJobRouteImport } from './routes/company/addJob'
import { Route as AuthVerificationRouteImport } from './routes/auth/verification'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthRolesRouteImport } from './routes/auth/roles'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthPasswordRouteImport } from './routes/auth/password'
import { Route as AuthOauthCallbackRouteImport } from './routes/auth/oauth-callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConnectGoogleRouteImport } from './routes/auth/connect-google'

const UploadResumeRoute = UploadResumeRouteImport.update({
  id: '/uploadResume',
  path: '/uploadResume',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skillGap',
  path: '/skillGap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeReportRoute = ResumeReportRouteImport.update({
  id: '/resumeReport',
  path: '/resumeReport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParsedResumeRoute = ParsedResumeRouteImport.update({
  id: '/parsedResume',
  path: '/parsedResume',
  getParentRoute: () => rootRouteImport,
} as any)
const MyResumesRoute = MyResumesRouteImport.update({
  id: '/myResumes',
  path: '/myResumes',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPlanRoute = LearningPlanRouteImport.update({
  id: '/learningPlan',
  path: '/learningPlan',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDetailsRoute = JobDetailsRouteImport.update({
  id: '/jobDetails',
  path: '/jobDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDetailWithSkillGapRoute = JobDetailWithSkillGapRouteImport.update({
  id: '/jobDetailWithSkillGap',
  path: '/jobDetailWithSkillGap',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingRoute = AccountSettingRouteImport.update({
  id: '/accountSetting',
  path: '/accountSetting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySupportRoute = CompanySupportRouteImport.update({
  id: '/company/support',
  path: '/company/support',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/company/settings',
  path: '/company/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileSetupRoute = CompanyProfileSetupRouteImport.update({
  id: '/company/profileSetup',
  path: '/company/profileSetup',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/company/jobs',
  path: '/company/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/company/dashboard',
  path: '/company/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/company/candidates',
  path: '/company/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidateDetailRoute = CompanyCandidateDetailRouteImport.update({
  id: '/company/candidateDetail',
  path: '/company/candidateDetail',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCadidateMatchRoute = CompanyCadidateMatchRouteImport.update({
  id: '/company/cadidateMatch',
  path: '/company/cadidateMatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAddJobRoute = CompanyAddJobRouteImport.update({
  id: '/company/addJob',
  path: '/company/addJob',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificationRoute = AuthVerificationRouteImport.update({
  id: '/auth/verification',
  path: '/auth/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/auth/roles',
  path: '/auth/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordRoute = AuthPasswordRouteImport.update({
  id: '/auth/password',
  path: '/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/auth/oauth-callback',
  path: '/auth/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnectGoogleRoute = AuthConnectGoogleRouteImport.update({
  id: '/auth/connect-google',
  path: '/auth/connect-google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountSetting': typeof AccountSettingRoute
  '/dashboard': typeof DashboardRoute
  '/jobDetailWithSkillGap': typeof JobDetailWithSkillGapRoute
  '/jobDetails': typeof JobDetailsRoute
  '/jobs': typeof JobsRoute
  '/learningPlan': typeof LearningPlanRoute
  '/myResumes': typeof MyResumesRoute
  '/parsedResume': typeof ParsedResumeRoute
  '/profile': typeof ProfileRoute
  '/resumeReport': typeof ResumeReportRoute
  '/skillGap': typeof SkillGapRoute
  '/uploadResume': typeof UploadResumeRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/addJob': typeof CompanyAddJobRoute
  '/company/cadidateMatch': typeof CompanyCadidateMatchRoute
  '/company/candidateDetail': typeof CompanyCandidateDetailRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profileSetup': typeof CompanyProfileSetupRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/support': typeof CompanySupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountSetting': typeof AccountSettingRoute
  '/dashboard': typeof DashboardRoute
  '/jobDetailWithSkillGap': typeof JobDetailWithSkillGapRoute
  '/jobDetails': typeof JobDetailsRoute
  '/jobs': typeof JobsRoute
  '/learningPlan': typeof LearningPlanRoute
  '/myResumes': typeof MyResumesRoute
  '/parsedResume': typeof ParsedResumeRoute
  '/profile': typeof ProfileRoute
  '/resumeReport': typeof ResumeReportRoute
  '/skillGap': typeof SkillGapRoute
  '/uploadResume': typeof UploadResumeRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/addJob': typeof CompanyAddJobRoute
  '/company/cadidateMatch': typeof CompanyCadidateMatchRoute
  '/company/candidateDetail': typeof CompanyCandidateDetailRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profileSetup': typeof CompanyProfileSetupRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/support': typeof CompanySupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountSetting': typeof AccountSettingRoute
  '/dashboard': typeof DashboardRoute
  '/jobDetailWithSkillGap': typeof JobDetailWithSkillGapRoute
  '/jobDetails': typeof JobDetailsRoute
  '/jobs': typeof JobsRoute
  '/learningPlan': typeof LearningPlanRoute
  '/myResumes': typeof MyResumesRoute
  '/parsedResume': typeof ParsedResumeRoute
  '/profile': typeof ProfileRoute
  '/resumeReport': typeof ResumeReportRoute
  '/skillGap': typeof SkillGapRoute
  '/uploadResume': typeof UploadResumeRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/addJob': typeof CompanyAddJobRoute
  '/company/cadidateMatch': typeof CompanyCadidateMatchRoute
  '/company/candidateDetail': typeof CompanyCandidateDetailRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profileSetup': typeof CompanyProfileSetupRoute
  '/company/settings': typeof CompanySettingsRoute
  '/company/support': typeof CompanySupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountSetting'
    | '/dashboard'
    | '/jobDetailWithSkillGap'
    | '/jobDetails'
    | '/jobs'
    | '/learningPlan'
    | '/myResumes'
    | '/parsedResume'
    | '/profile'
    | '/resumeReport'
    | '/skillGap'
    | '/uploadResume'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/roles'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/addJob'
    | '/company/cadidateMatch'
    | '/company/candidateDetail'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/jobs'
    | '/company/profileSetup'
    | '/company/settings'
    | '/company/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountSetting'
    | '/dashboard'
    | '/jobDetailWithSkillGap'
    | '/jobDetails'
    | '/jobs'
    | '/learningPlan'
    | '/myResumes'
    | '/parsedResume'
    | '/profile'
    | '/resumeReport'
    | '/skillGap'
    | '/uploadResume'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/roles'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/addJob'
    | '/company/cadidateMatch'
    | '/company/candidateDetail'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/jobs'
    | '/company/profileSetup'
    | '/company/settings'
    | '/company/support'
  id:
    | '__root__'
    | '/'
    | '/accountSetting'
    | '/dashboard'
    | '/jobDetailWithSkillGap'
    | '/jobDetails'
    | '/jobs'
    | '/learningPlan'
    | '/myResumes'
    | '/parsedResume'
    | '/profile'
    | '/resumeReport'
    | '/skillGap'
    | '/uploadResume'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/roles'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/addJob'
    | '/company/cadidateMatch'
    | '/company/candidateDetail'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/jobs'
    | '/company/profileSetup'
    | '/company/settings'
    | '/company/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSettingRoute: typeof AccountSettingRoute
  DashboardRoute: typeof DashboardRoute
  JobDetailWithSkillGapRoute: typeof JobDetailWithSkillGapRoute
  JobDetailsRoute: typeof JobDetailsRoute
  JobsRoute: typeof JobsRoute
  LearningPlanRoute: typeof LearningPlanRoute
  MyResumesRoute: typeof MyResumesRoute
  ParsedResumeRoute: typeof ParsedResumeRoute
  ProfileRoute: typeof ProfileRoute
  ResumeReportRoute: typeof ResumeReportRoute
  SkillGapRoute: typeof SkillGapRoute
  UploadResumeRoute: typeof UploadResumeRoute
  AuthConnectGoogleRoute: typeof AuthConnectGoogleRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  AuthPasswordRoute: typeof AuthPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerificationRoute: typeof AuthVerificationRoute
  CompanyAddJobRoute: typeof CompanyAddJobRoute
  CompanyCadidateMatchRoute: typeof CompanyCadidateMatchRoute
  CompanyCandidateDetailRoute: typeof CompanyCandidateDetailRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRoute
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyProfileSetupRoute: typeof CompanyProfileSetupRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  CompanySupportRoute: typeof CompanySupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploadResume': {
      id: '/uploadResume'
      path: '/uploadResume'
      fullPath: '/uploadResume'
      preLoaderRoute: typeof UploadResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skillGap': {
      id: '/skillGap'
      path: '/skillGap'
      fullPath: '/skillGap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumeReport': {
      id: '/resumeReport'
      path: '/resumeReport'
      fullPath: '/resumeReport'
      preLoaderRoute: typeof ResumeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsedResume': {
      id: '/parsedResume'
      path: '/parsedResume'
      fullPath: '/parsedResume'
      preLoaderRoute: typeof ParsedResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myResumes': {
      id: '/myResumes'
      path: '/myResumes'
      fullPath: '/myResumes'
      preLoaderRoute: typeof MyResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learningPlan': {
      id: '/learningPlan'
      path: '/learningPlan'
      fullPath: '/learningPlan'
      preLoaderRoute: typeof LearningPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobDetails': {
      id: '/jobDetails'
      path: '/jobDetails'
      fullPath: '/jobDetails'
      preLoaderRoute: typeof JobDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobDetailWithSkillGap': {
      id: '/jobDetailWithSkillGap'
      path: '/jobDetailWithSkillGap'
      fullPath: '/jobDetailWithSkillGap'
      preLoaderRoute: typeof JobDetailWithSkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountSetting': {
      id: '/accountSetting'
      path: '/accountSetting'
      fullPath: '/accountSetting'
      preLoaderRoute: typeof AccountSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/support': {
      id: '/company/support'
      path: '/company/support'
      fullPath: '/company/support'
      preLoaderRoute: typeof CompanySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/company/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/profileSetup': {
      id: '/company/profileSetup'
      path: '/company/profileSetup'
      fullPath: '/company/profileSetup'
      preLoaderRoute: typeof CompanyProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs': {
      id: '/company/jobs'
      path: '/company/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/company/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/company/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidateDetail': {
      id: '/company/candidateDetail'
      path: '/company/candidateDetail'
      fullPath: '/company/candidateDetail'
      preLoaderRoute: typeof CompanyCandidateDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/cadidateMatch': {
      id: '/company/cadidateMatch'
      path: '/company/cadidateMatch'
      fullPath: '/company/cadidateMatch'
      preLoaderRoute: typeof CompanyCadidateMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/addJob': {
      id: '/company/addJob'
      path: '/company/addJob'
      fullPath: '/company/addJob'
      preLoaderRoute: typeof CompanyAddJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verification': {
      id: '/auth/verification'
      path: '/auth/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/roles': {
      id: '/auth/roles'
      path: '/auth/roles'
      fullPath: '/auth/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password': {
      id: '/auth/password'
      path: '/auth/password'
      fullPath: '/auth/password'
      preLoaderRoute: typeof AuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oauth-callback': {
      id: '/auth/oauth-callback'
      path: '/auth/oauth-callback'
      fullPath: '/auth/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connect-google': {
      id: '/auth/connect-google'
      path: '/auth/connect-google'
      fullPath: '/auth/connect-google'
      preLoaderRoute: typeof AuthConnectGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSettingRoute: AccountSettingRoute,
  DashboardRoute: DashboardRoute,
  JobDetailWithSkillGapRoute: JobDetailWithSkillGapRoute,
  JobDetailsRoute: JobDetailsRoute,
  JobsRoute: JobsRoute,
  LearningPlanRoute: LearningPlanRoute,
  MyResumesRoute: MyResumesRoute,
  ParsedResumeRoute: ParsedResumeRoute,
  ProfileRoute: ProfileRoute,
  ResumeReportRoute: ResumeReportRoute,
  SkillGapRoute: SkillGapRoute,
  UploadResumeRoute: UploadResumeRoute,
  AuthConnectGoogleRoute: AuthConnectGoogleRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  AuthPasswordRoute: AuthPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerificationRoute: AuthVerificationRoute,
  CompanyAddJobRoute: CompanyAddJobRoute,
  CompanyCadidateMatchRoute: CompanyCadidateMatchRoute,
  CompanyCandidateDetailRoute: CompanyCandidateDetailRoute,
  CompanyCandidatesRoute: CompanyCandidatesRoute,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyProfileSetupRoute: CompanyProfileSetupRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  CompanySupportRoute: CompanySupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
