/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobSeekerUploadResumeRouteImport } from './routes/job-seeker/uploadResume'
import { Route as JobSeekerResumeReportRouteImport } from './routes/job-seeker/resumeReport'
import { Route as JobSeekerProfileRouteImport } from './routes/job-seeker/profile'
import { Route as JobSeekerMyResumesRouteImport } from './routes/job-seeker/myResumes'
import { Route as JobSeekerJobsRouteImport } from './routes/job-seeker/jobs'
import { Route as JobSeekerJobDetailsRouteImport } from './routes/job-seeker/job-details'
import { Route as JobSeekerDashboardRouteImport } from './routes/job-seeker/dashboard'
import { Route as JobSeekerAccountSettingsRouteImport } from './routes/job-seeker/account-settings'
import { Route as CompanySettingsRouteImport } from './routes/company/settings'
import { Route as CompanyProfileRouteImport } from './routes/company/profile'
import { Route as CompanyJobsRouteImport } from './routes/company/jobs'
import { Route as CompanyJobDetailsRouteImport } from './routes/company/jobDetails'
import { Route as CompanyEditJobRouteImport } from './routes/company/editJob'
import { Route as CompanyDashboardRouteImport } from './routes/company/dashboard'
import { Route as CompanyCandidatesRouteImport } from './routes/company/candidates'
import { Route as CompanyApplicantsRouteImport } from './routes/company/applicants'
import { Route as CompanyApplicantDetailRouteImport } from './routes/company/applicant-detail'
import { Route as CompanyAddJobRouteImport } from './routes/company/add-job'
import { Route as AuthVerificationRouteImport } from './routes/auth/verification'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthRolesRouteImport } from './routes/auth/roles'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthPasswordRouteImport } from './routes/auth/password'
import { Route as AuthOauthCallbackRouteImport } from './routes/auth/oauth-callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConnectGoogleRouteImport } from './routes/auth/connect-google'
import { Route as JobSeekerParsedResumeResumeIdRouteImport } from './routes/job-seeker/parsedResume/$resumeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerUploadResumeRoute = JobSeekerUploadResumeRouteImport.update({
  id: '/job-seeker/uploadResume',
  path: '/job-seeker/uploadResume',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerResumeReportRoute = JobSeekerResumeReportRouteImport.update({
  id: '/job-seeker/resumeReport',
  path: '/job-seeker/resumeReport',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerProfileRoute = JobSeekerProfileRouteImport.update({
  id: '/job-seeker/profile',
  path: '/job-seeker/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerMyResumesRoute = JobSeekerMyResumesRouteImport.update({
  id: '/job-seeker/myResumes',
  path: '/job-seeker/myResumes',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerJobsRoute = JobSeekerJobsRouteImport.update({
  id: '/job-seeker/jobs',
  path: '/job-seeker/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerJobDetailsRoute = JobSeekerJobDetailsRouteImport.update({
  id: '/job-seeker/job-details',
  path: '/job-seeker/job-details',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerDashboardRoute = JobSeekerDashboardRouteImport.update({
  id: '/job-seeker/dashboard',
  path: '/job-seeker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerAccountSettingsRoute =
  JobSeekerAccountSettingsRouteImport.update({
    id: '/job-seeker/account-settings',
    path: '/job-seeker/account-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/company/settings',
  path: '/company/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company/profile',
  path: '/company/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/company/jobs',
  path: '/company/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyJobDetailsRoute = CompanyJobDetailsRouteImport.update({
  id: '/company/jobDetails',
  path: '/company/jobDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyEditJobRoute = CompanyEditJobRouteImport.update({
  id: '/company/editJob',
  path: '/company/editJob',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/company/dashboard',
  path: '/company/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/company/candidates',
  path: '/company/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyApplicantsRoute = CompanyApplicantsRouteImport.update({
  id: '/company/applicants',
  path: '/company/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyApplicantDetailRoute = CompanyApplicantDetailRouteImport.update({
  id: '/company/applicant-detail',
  path: '/company/applicant-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAddJobRoute = CompanyAddJobRouteImport.update({
  id: '/company/add-job',
  path: '/company/add-job',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificationRoute = AuthVerificationRouteImport.update({
  id: '/auth/verification',
  path: '/auth/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRolesRoute = AuthRolesRouteImport.update({
  id: '/auth/roles',
  path: '/auth/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordRoute = AuthPasswordRouteImport.update({
  id: '/auth/password',
  path: '/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/auth/oauth-callback',
  path: '/auth/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnectGoogleRoute = AuthConnectGoogleRouteImport.update({
  id: '/auth/connect-google',
  path: '/auth/connect-google',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerParsedResumeResumeIdRoute =
  JobSeekerParsedResumeResumeIdRouteImport.update({
    id: '/job-seeker/parsedResume/$resumeId',
    path: '/job-seeker/parsedResume/$resumeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/add-job': typeof CompanyAddJobRoute
  '/company/applicant-detail': typeof CompanyApplicantDetailRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/editJob': typeof CompanyEditJobRoute
  '/company/jobDetails': typeof CompanyJobDetailsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profile': typeof CompanyProfileRoute
  '/company/settings': typeof CompanySettingsRoute
  '/job-seeker/account-settings': typeof JobSeekerAccountSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/job-details': typeof JobSeekerJobDetailsRoute
  '/job-seeker/jobs': typeof JobSeekerJobsRoute
  '/job-seeker/myResumes': typeof JobSeekerMyResumesRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/job-seeker/resumeReport': typeof JobSeekerResumeReportRoute
  '/job-seeker/uploadResume': typeof JobSeekerUploadResumeRoute
  '/job-seeker/parsedResume/$resumeId': typeof JobSeekerParsedResumeResumeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/add-job': typeof CompanyAddJobRoute
  '/company/applicant-detail': typeof CompanyApplicantDetailRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/editJob': typeof CompanyEditJobRoute
  '/company/jobDetails': typeof CompanyJobDetailsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profile': typeof CompanyProfileRoute
  '/company/settings': typeof CompanySettingsRoute
  '/job-seeker/account-settings': typeof JobSeekerAccountSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/job-details': typeof JobSeekerJobDetailsRoute
  '/job-seeker/jobs': typeof JobSeekerJobsRoute
  '/job-seeker/myResumes': typeof JobSeekerMyResumesRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/job-seeker/resumeReport': typeof JobSeekerResumeReportRoute
  '/job-seeker/uploadResume': typeof JobSeekerUploadResumeRoute
  '/job-seeker/parsedResume/$resumeId': typeof JobSeekerParsedResumeResumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/roles': typeof AuthRolesRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/add-job': typeof CompanyAddJobRoute
  '/company/applicant-detail': typeof CompanyApplicantDetailRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/editJob': typeof CompanyEditJobRoute
  '/company/jobDetails': typeof CompanyJobDetailsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profile': typeof CompanyProfileRoute
  '/company/settings': typeof CompanySettingsRoute
  '/job-seeker/account-settings': typeof JobSeekerAccountSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/job-details': typeof JobSeekerJobDetailsRoute
  '/job-seeker/jobs': typeof JobSeekerJobsRoute
  '/job-seeker/myResumes': typeof JobSeekerMyResumesRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/job-seeker/resumeReport': typeof JobSeekerResumeReportRoute
  '/job-seeker/uploadResume': typeof JobSeekerUploadResumeRoute
  '/job-seeker/parsedResume/$resumeId': typeof JobSeekerParsedResumeResumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/roles'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/add-job'
    | '/company/applicant-detail'
    | '/company/applicants'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/editJob'
    | '/company/jobDetails'
    | '/company/jobs'
    | '/company/profile'
    | '/company/settings'
    | '/job-seeker/account-settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/job-details'
    | '/job-seeker/jobs'
    | '/job-seeker/myResumes'
    | '/job-seeker/profile'
    | '/job-seeker/resumeReport'
    | '/job-seeker/uploadResume'
    | '/job-seeker/parsedResume/$resumeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/roles'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/add-job'
    | '/company/applicant-detail'
    | '/company/applicants'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/editJob'
    | '/company/jobDetails'
    | '/company/jobs'
    | '/company/profile'
    | '/company/settings'
    | '/job-seeker/account-settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/job-details'
    | '/job-seeker/jobs'
    | '/job-seeker/myResumes'
    | '/job-seeker/profile'
    | '/job-seeker/resumeReport'
    | '/job-seeker/uploadResume'
    | '/job-seeker/parsedResume/$resumeId'
  id:
    | '__root__'
    | '/'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/roles'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/add-job'
    | '/company/applicant-detail'
    | '/company/applicants'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/editJob'
    | '/company/jobDetails'
    | '/company/jobs'
    | '/company/profile'
    | '/company/settings'
    | '/job-seeker/account-settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/job-details'
    | '/job-seeker/jobs'
    | '/job-seeker/myResumes'
    | '/job-seeker/profile'
    | '/job-seeker/resumeReport'
    | '/job-seeker/uploadResume'
    | '/job-seeker/parsedResume/$resumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthConnectGoogleRoute: typeof AuthConnectGoogleRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  AuthPasswordRoute: typeof AuthPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthRolesRoute: typeof AuthRolesRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerificationRoute: typeof AuthVerificationRoute
  CompanyAddJobRoute: typeof CompanyAddJobRoute
  CompanyApplicantDetailRoute: typeof CompanyApplicantDetailRoute
  CompanyApplicantsRoute: typeof CompanyApplicantsRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRoute
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyEditJobRoute: typeof CompanyEditJobRoute
  CompanyJobDetailsRoute: typeof CompanyJobDetailsRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  JobSeekerAccountSettingsRoute: typeof JobSeekerAccountSettingsRoute
  JobSeekerDashboardRoute: typeof JobSeekerDashboardRoute
  JobSeekerJobDetailsRoute: typeof JobSeekerJobDetailsRoute
  JobSeekerJobsRoute: typeof JobSeekerJobsRoute
  JobSeekerMyResumesRoute: typeof JobSeekerMyResumesRoute
  JobSeekerProfileRoute: typeof JobSeekerProfileRoute
  JobSeekerResumeReportRoute: typeof JobSeekerResumeReportRoute
  JobSeekerUploadResumeRoute: typeof JobSeekerUploadResumeRoute
  JobSeekerParsedResumeResumeIdRoute: typeof JobSeekerParsedResumeResumeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/uploadResume': {
      id: '/job-seeker/uploadResume'
      path: '/job-seeker/uploadResume'
      fullPath: '/job-seeker/uploadResume'
      preLoaderRoute: typeof JobSeekerUploadResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/resumeReport': {
      id: '/job-seeker/resumeReport'
      path: '/job-seeker/resumeReport'
      fullPath: '/job-seeker/resumeReport'
      preLoaderRoute: typeof JobSeekerResumeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/profile': {
      id: '/job-seeker/profile'
      path: '/job-seeker/profile'
      fullPath: '/job-seeker/profile'
      preLoaderRoute: typeof JobSeekerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/myResumes': {
      id: '/job-seeker/myResumes'
      path: '/job-seeker/myResumes'
      fullPath: '/job-seeker/myResumes'
      preLoaderRoute: typeof JobSeekerMyResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/jobs': {
      id: '/job-seeker/jobs'
      path: '/job-seeker/jobs'
      fullPath: '/job-seeker/jobs'
      preLoaderRoute: typeof JobSeekerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/job-details': {
      id: '/job-seeker/job-details'
      path: '/job-seeker/job-details'
      fullPath: '/job-seeker/job-details'
      preLoaderRoute: typeof JobSeekerJobDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/dashboard': {
      id: '/job-seeker/dashboard'
      path: '/job-seeker/dashboard'
      fullPath: '/job-seeker/dashboard'
      preLoaderRoute: typeof JobSeekerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/account-settings': {
      id: '/job-seeker/account-settings'
      path: '/job-seeker/account-settings'
      fullPath: '/job-seeker/account-settings'
      preLoaderRoute: typeof JobSeekerAccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/company/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/profile': {
      id: '/company/profile'
      path: '/company/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobs': {
      id: '/company/jobs'
      path: '/company/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/jobDetails': {
      id: '/company/jobDetails'
      path: '/company/jobDetails'
      fullPath: '/company/jobDetails'
      preLoaderRoute: typeof CompanyJobDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/editJob': {
      id: '/company/editJob'
      path: '/company/editJob'
      fullPath: '/company/editJob'
      preLoaderRoute: typeof CompanyEditJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/company/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/company/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/applicants': {
      id: '/company/applicants'
      path: '/company/applicants'
      fullPath: '/company/applicants'
      preLoaderRoute: typeof CompanyApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/applicant-detail': {
      id: '/company/applicant-detail'
      path: '/company/applicant-detail'
      fullPath: '/company/applicant-detail'
      preLoaderRoute: typeof CompanyApplicantDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/add-job': {
      id: '/company/add-job'
      path: '/company/add-job'
      fullPath: '/company/add-job'
      preLoaderRoute: typeof CompanyAddJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verification': {
      id: '/auth/verification'
      path: '/auth/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/roles': {
      id: '/auth/roles'
      path: '/auth/roles'
      fullPath: '/auth/roles'
      preLoaderRoute: typeof AuthRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password': {
      id: '/auth/password'
      path: '/auth/password'
      fullPath: '/auth/password'
      preLoaderRoute: typeof AuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oauth-callback': {
      id: '/auth/oauth-callback'
      path: '/auth/oauth-callback'
      fullPath: '/auth/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connect-google': {
      id: '/auth/connect-google'
      path: '/auth/connect-google'
      fullPath: '/auth/connect-google'
      preLoaderRoute: typeof AuthConnectGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/parsedResume/$resumeId': {
      id: '/job-seeker/parsedResume/$resumeId'
      path: '/job-seeker/parsedResume/$resumeId'
      fullPath: '/job-seeker/parsedResume/$resumeId'
      preLoaderRoute: typeof JobSeekerParsedResumeResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthConnectGoogleRoute: AuthConnectGoogleRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  AuthPasswordRoute: AuthPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthRolesRoute: AuthRolesRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerificationRoute: AuthVerificationRoute,
  CompanyAddJobRoute: CompanyAddJobRoute,
  CompanyApplicantDetailRoute: CompanyApplicantDetailRoute,
  CompanyApplicantsRoute: CompanyApplicantsRoute,
  CompanyCandidatesRoute: CompanyCandidatesRoute,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyEditJobRoute: CompanyEditJobRoute,
  CompanyJobDetailsRoute: CompanyJobDetailsRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  JobSeekerAccountSettingsRoute: JobSeekerAccountSettingsRoute,
  JobSeekerDashboardRoute: JobSeekerDashboardRoute,
  JobSeekerJobDetailsRoute: JobSeekerJobDetailsRoute,
  JobSeekerJobsRoute: JobSeekerJobsRoute,
  JobSeekerMyResumesRoute: JobSeekerMyResumesRoute,
  JobSeekerProfileRoute: JobSeekerProfileRoute,
  JobSeekerResumeReportRoute: JobSeekerResumeReportRoute,
  JobSeekerUploadResumeRoute: JobSeekerUploadResumeRoute,
  JobSeekerParsedResumeResumeIdRoute: JobSeekerParsedResumeResumeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
