/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as JobSeekerRouteImport } from './routes/job-seeker'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobSeekerUploadResumeRouteImport } from './routes/job-seeker/upload-resume'
import { Route as JobSeekerResumeReportRouteImport } from './routes/job-seeker/resume-report'
import { Route as JobSeekerProfileRouteImport } from './routes/job-seeker/profile'
import { Route as JobSeekerMyResumesRouteImport } from './routes/job-seeker/my-resumes'
import { Route as JobSeekerJobsRouteImport } from './routes/job-seeker/jobs'
import { Route as JobSeekerJobDetailsRouteImport } from './routes/job-seeker/job-details'
import { Route as JobSeekerDashboardRouteImport } from './routes/job-seeker/dashboard'
import { Route as JobSeekerAccountSettingsRouteImport } from './routes/job-seeker/account-settings'
import { Route as CompanySettingsRouteImport } from './routes/company/settings'
import { Route as CompanyProfileRouteImport } from './routes/company/profile'
import { Route as CompanyJobsRouteImport } from './routes/company/jobs'
import { Route as CompanyJobDetailsRouteImport } from './routes/company/job-details'
import { Route as CompanyEditJobRouteImport } from './routes/company/edit-job'
import { Route as CompanyDashboardRouteImport } from './routes/company/dashboard'
import { Route as CompanyCandidatesRouteImport } from './routes/company/candidates'
import { Route as CompanyApplicantsRouteImport } from './routes/company/applicants'
import { Route as CompanyApplicantDetailRouteImport } from './routes/company/applicant-detail'
import { Route as CompanyAddJobRouteImport } from './routes/company/add-job'
import { Route as AuthVerificationRouteImport } from './routes/auth/verification'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthPasswordRouteImport } from './routes/auth/password'
import { Route as AuthOauthCallbackRouteImport } from './routes/auth/oauth-callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConnectGoogleRouteImport } from './routes/auth/connect-google'
import { Route as JobSeekerParsedResumeResumeIdRouteImport } from './routes/job-seeker/parsed-resume/$resumeId'

const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerRoute = JobSeekerRouteImport.update({
  id: '/job-seeker',
  path: '/job-seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekerUploadResumeRoute = JobSeekerUploadResumeRouteImport.update({
  id: '/upload-resume',
  path: '/upload-resume',
  getParentRoute: () => JobSeekerRoute,
} as any)
const JobSeekerResumeReportRoute = JobSeekerResumeReportRouteImport.update({
  id: '/resume-report',
  path: '/resume-report',
  getParentRoute: () => JobSeekerRoute,
} as any)
const JobSeekerProfileRoute = JobSeekerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => JobSeekerRoute,
} as any)
const JobSeekerMyResumesRoute = JobSeekerMyResumesRouteImport.update({
  id: '/my-resumes',
  path: '/my-resumes',
  getParentRoute: () => JobSeekerRoute,
} as any)
const JobSeekerJobsRoute = JobSeekerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => JobSeekerRoute,
} as any)
const JobSeekerJobDetailsRoute = JobSeekerJobDetailsRouteImport.update({
  id: '/job-details',
  path: '/job-details',
  getParentRoute: () => JobSeekerRoute,
} as any)
const JobSeekerDashboardRoute = JobSeekerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => JobSeekerRoute,
} as any)
const JobSeekerAccountSettingsRoute =
  JobSeekerAccountSettingsRouteImport.update({
    id: '/account-settings',
    path: '/account-settings',
    getParentRoute: () => JobSeekerRoute,
  } as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyJobDetailsRoute = CompanyJobDetailsRouteImport.update({
  id: '/job-details',
  path: '/job-details',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyEditJobRoute = CompanyEditJobRouteImport.update({
  id: '/edit-job',
  path: '/edit-job',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyCandidatesRoute = CompanyCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyApplicantsRoute = CompanyApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyApplicantDetailRoute = CompanyApplicantDetailRouteImport.update({
  id: '/applicant-detail',
  path: '/applicant-detail',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyAddJobRoute = CompanyAddJobRouteImport.update({
  id: '/add-job',
  path: '/add-job',
  getParentRoute: () => CompanyRoute,
} as any)
const AuthVerificationRoute = AuthVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPasswordRoute = AuthPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConnectGoogleRoute = AuthConnectGoogleRouteImport.update({
  id: '/connect-google',
  path: '/connect-google',
  getParentRoute: () => AuthRoute,
} as any)
const JobSeekerParsedResumeResumeIdRoute =
  JobSeekerParsedResumeResumeIdRouteImport.update({
    id: '/parsed-resume/$resumeId',
    path: '/parsed-resume/$resumeId',
    getParentRoute: () => JobSeekerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/job-seeker': typeof JobSeekerRouteWithChildren
  '/roles': typeof RolesRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/add-job': typeof CompanyAddJobRoute
  '/company/applicant-detail': typeof CompanyApplicantDetailRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/edit-job': typeof CompanyEditJobRoute
  '/company/job-details': typeof CompanyJobDetailsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profile': typeof CompanyProfileRoute
  '/company/settings': typeof CompanySettingsRoute
  '/job-seeker/account-settings': typeof JobSeekerAccountSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/job-details': typeof JobSeekerJobDetailsRoute
  '/job-seeker/jobs': typeof JobSeekerJobsRoute
  '/job-seeker/my-resumes': typeof JobSeekerMyResumesRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/job-seeker/resume-report': typeof JobSeekerResumeReportRoute
  '/job-seeker/upload-resume': typeof JobSeekerUploadResumeRoute
  '/job-seeker/parsed-resume/$resumeId': typeof JobSeekerParsedResumeResumeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/job-seeker': typeof JobSeekerRouteWithChildren
  '/roles': typeof RolesRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/add-job': typeof CompanyAddJobRoute
  '/company/applicant-detail': typeof CompanyApplicantDetailRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/edit-job': typeof CompanyEditJobRoute
  '/company/job-details': typeof CompanyJobDetailsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profile': typeof CompanyProfileRoute
  '/company/settings': typeof CompanySettingsRoute
  '/job-seeker/account-settings': typeof JobSeekerAccountSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/job-details': typeof JobSeekerJobDetailsRoute
  '/job-seeker/jobs': typeof JobSeekerJobsRoute
  '/job-seeker/my-resumes': typeof JobSeekerMyResumesRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/job-seeker/resume-report': typeof JobSeekerResumeReportRoute
  '/job-seeker/upload-resume': typeof JobSeekerUploadResumeRoute
  '/job-seeker/parsed-resume/$resumeId': typeof JobSeekerParsedResumeResumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/auth': typeof AuthRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/job-seeker': typeof JobSeekerRouteWithChildren
  '/roles': typeof RolesRoute
  '/auth/connect-google': typeof AuthConnectGoogleRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/auth/password': typeof AuthPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/company/add-job': typeof CompanyAddJobRoute
  '/company/applicant-detail': typeof CompanyApplicantDetailRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/candidates': typeof CompanyCandidatesRoute
  '/company/dashboard': typeof CompanyDashboardRoute
  '/company/edit-job': typeof CompanyEditJobRoute
  '/company/job-details': typeof CompanyJobDetailsRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/profile': typeof CompanyProfileRoute
  '/company/settings': typeof CompanySettingsRoute
  '/job-seeker/account-settings': typeof JobSeekerAccountSettingsRoute
  '/job-seeker/dashboard': typeof JobSeekerDashboardRoute
  '/job-seeker/job-details': typeof JobSeekerJobDetailsRoute
  '/job-seeker/jobs': typeof JobSeekerJobsRoute
  '/job-seeker/my-resumes': typeof JobSeekerMyResumesRoute
  '/job-seeker/profile': typeof JobSeekerProfileRoute
  '/job-seeker/resume-report': typeof JobSeekerResumeReportRoute
  '/job-seeker/upload-resume': typeof JobSeekerUploadResumeRoute
  '/job-seeker/parsed-resume/$resumeId': typeof JobSeekerParsedResumeResumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/auth'
    | '/company'
    | '/job-seeker'
    | '/roles'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/add-job'
    | '/company/applicant-detail'
    | '/company/applicants'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/edit-job'
    | '/company/job-details'
    | '/company/jobs'
    | '/company/profile'
    | '/company/settings'
    | '/job-seeker/account-settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/job-details'
    | '/job-seeker/jobs'
    | '/job-seeker/my-resumes'
    | '/job-seeker/profile'
    | '/job-seeker/resume-report'
    | '/job-seeker/upload-resume'
    | '/job-seeker/parsed-resume/$resumeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/auth'
    | '/company'
    | '/job-seeker'
    | '/roles'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/add-job'
    | '/company/applicant-detail'
    | '/company/applicants'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/edit-job'
    | '/company/job-details'
    | '/company/jobs'
    | '/company/profile'
    | '/company/settings'
    | '/job-seeker/account-settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/job-details'
    | '/job-seeker/jobs'
    | '/job-seeker/my-resumes'
    | '/job-seeker/profile'
    | '/job-seeker/resume-report'
    | '/job-seeker/upload-resume'
    | '/job-seeker/parsed-resume/$resumeId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/auth'
    | '/company'
    | '/job-seeker'
    | '/roles'
    | '/auth/connect-google'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/oauth-callback'
    | '/auth/password'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/auth/signup'
    | '/auth/verification'
    | '/company/add-job'
    | '/company/applicant-detail'
    | '/company/applicants'
    | '/company/candidates'
    | '/company/dashboard'
    | '/company/edit-job'
    | '/company/job-details'
    | '/company/jobs'
    | '/company/profile'
    | '/company/settings'
    | '/job-seeker/account-settings'
    | '/job-seeker/dashboard'
    | '/job-seeker/job-details'
    | '/job-seeker/jobs'
    | '/job-seeker/my-resumes'
    | '/job-seeker/profile'
    | '/job-seeker/resume-report'
    | '/job-seeker/upload-resume'
    | '/job-seeker/parsed-resume/$resumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AuthRoute: typeof AuthRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  JobSeekerRoute: typeof JobSeekerRouteWithChildren
  RolesRoute: typeof RolesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker': {
      id: '/job-seeker'
      path: '/job-seeker'
      fullPath: '/job-seeker'
      preLoaderRoute: typeof JobSeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seeker/upload-resume': {
      id: '/job-seeker/upload-resume'
      path: '/upload-resume'
      fullPath: '/job-seeker/upload-resume'
      preLoaderRoute: typeof JobSeekerUploadResumeRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/job-seeker/resume-report': {
      id: '/job-seeker/resume-report'
      path: '/resume-report'
      fullPath: '/job-seeker/resume-report'
      preLoaderRoute: typeof JobSeekerResumeReportRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/job-seeker/profile': {
      id: '/job-seeker/profile'
      path: '/profile'
      fullPath: '/job-seeker/profile'
      preLoaderRoute: typeof JobSeekerProfileRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/job-seeker/my-resumes': {
      id: '/job-seeker/my-resumes'
      path: '/my-resumes'
      fullPath: '/job-seeker/my-resumes'
      preLoaderRoute: typeof JobSeekerMyResumesRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/job-seeker/jobs': {
      id: '/job-seeker/jobs'
      path: '/jobs'
      fullPath: '/job-seeker/jobs'
      preLoaderRoute: typeof JobSeekerJobsRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/job-seeker/job-details': {
      id: '/job-seeker/job-details'
      path: '/job-details'
      fullPath: '/job-seeker/job-details'
      preLoaderRoute: typeof JobSeekerJobDetailsRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/job-seeker/dashboard': {
      id: '/job-seeker/dashboard'
      path: '/dashboard'
      fullPath: '/job-seeker/dashboard'
      preLoaderRoute: typeof JobSeekerDashboardRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/job-seeker/account-settings': {
      id: '/job-seeker/account-settings'
      path: '/account-settings'
      fullPath: '/job-seeker/account-settings'
      preLoaderRoute: typeof JobSeekerAccountSettingsRouteImport
      parentRoute: typeof JobSeekerRoute
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/profile': {
      id: '/company/profile'
      path: '/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/jobs': {
      id: '/company/jobs'
      path: '/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/job-details': {
      id: '/company/job-details'
      path: '/job-details'
      fullPath: '/company/job-details'
      preLoaderRoute: typeof CompanyJobDetailsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/edit-job': {
      id: '/company/edit-job'
      path: '/edit-job'
      fullPath: '/company/edit-job'
      preLoaderRoute: typeof CompanyEditJobRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/dashboard': {
      id: '/company/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/candidates': {
      id: '/company/candidates'
      path: '/candidates'
      fullPath: '/company/candidates'
      preLoaderRoute: typeof CompanyCandidatesRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/applicants': {
      id: '/company/applicants'
      path: '/applicants'
      fullPath: '/company/applicants'
      preLoaderRoute: typeof CompanyApplicantsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/applicant-detail': {
      id: '/company/applicant-detail'
      path: '/applicant-detail'
      fullPath: '/company/applicant-detail'
      preLoaderRoute: typeof CompanyApplicantDetailRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/add-job': {
      id: '/company/add-job'
      path: '/add-job'
      fullPath: '/company/add-job'
      preLoaderRoute: typeof CompanyAddJobRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/auth/verification': {
      id: '/auth/verification'
      path: '/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/password': {
      id: '/auth/password'
      path: '/password'
      fullPath: '/auth/password'
      preLoaderRoute: typeof AuthPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/oauth-callback': {
      id: '/auth/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/auth/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/connect-google': {
      id: '/auth/connect-google'
      path: '/connect-google'
      fullPath: '/auth/connect-google'
      preLoaderRoute: typeof AuthConnectGoogleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/job-seeker/parsed-resume/$resumeId': {
      id: '/job-seeker/parsed-resume/$resumeId'
      path: '/parsed-resume/$resumeId'
      fullPath: '/job-seeker/parsed-resume/$resumeId'
      preLoaderRoute: typeof JobSeekerParsedResumeResumeIdRouteImport
      parentRoute: typeof JobSeekerRoute
    }
  }
}

interface AuthRouteChildren {
  AuthConnectGoogleRoute: typeof AuthConnectGoogleRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  AuthPasswordRoute: typeof AuthPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerificationRoute: typeof AuthVerificationRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConnectGoogleRoute: AuthConnectGoogleRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  AuthPasswordRoute: AuthPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerificationRoute: AuthVerificationRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CompanyRouteChildren {
  CompanyAddJobRoute: typeof CompanyAddJobRoute
  CompanyApplicantDetailRoute: typeof CompanyApplicantDetailRoute
  CompanyApplicantsRoute: typeof CompanyApplicantsRoute
  CompanyCandidatesRoute: typeof CompanyCandidatesRoute
  CompanyDashboardRoute: typeof CompanyDashboardRoute
  CompanyEditJobRoute: typeof CompanyEditJobRoute
  CompanyJobDetailsRoute: typeof CompanyJobDetailsRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAddJobRoute: CompanyAddJobRoute,
  CompanyApplicantDetailRoute: CompanyApplicantDetailRoute,
  CompanyApplicantsRoute: CompanyApplicantsRoute,
  CompanyCandidatesRoute: CompanyCandidatesRoute,
  CompanyDashboardRoute: CompanyDashboardRoute,
  CompanyEditJobRoute: CompanyEditJobRoute,
  CompanyJobDetailsRoute: CompanyJobDetailsRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  CompanySettingsRoute: CompanySettingsRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface JobSeekerRouteChildren {
  JobSeekerAccountSettingsRoute: typeof JobSeekerAccountSettingsRoute
  JobSeekerDashboardRoute: typeof JobSeekerDashboardRoute
  JobSeekerJobDetailsRoute: typeof JobSeekerJobDetailsRoute
  JobSeekerJobsRoute: typeof JobSeekerJobsRoute
  JobSeekerMyResumesRoute: typeof JobSeekerMyResumesRoute
  JobSeekerProfileRoute: typeof JobSeekerProfileRoute
  JobSeekerResumeReportRoute: typeof JobSeekerResumeReportRoute
  JobSeekerUploadResumeRoute: typeof JobSeekerUploadResumeRoute
  JobSeekerParsedResumeResumeIdRoute: typeof JobSeekerParsedResumeResumeIdRoute
}

const JobSeekerRouteChildren: JobSeekerRouteChildren = {
  JobSeekerAccountSettingsRoute: JobSeekerAccountSettingsRoute,
  JobSeekerDashboardRoute: JobSeekerDashboardRoute,
  JobSeekerJobDetailsRoute: JobSeekerJobDetailsRoute,
  JobSeekerJobsRoute: JobSeekerJobsRoute,
  JobSeekerMyResumesRoute: JobSeekerMyResumesRoute,
  JobSeekerProfileRoute: JobSeekerProfileRoute,
  JobSeekerResumeReportRoute: JobSeekerResumeReportRoute,
  JobSeekerUploadResumeRoute: JobSeekerUploadResumeRoute,
  JobSeekerParsedResumeResumeIdRoute: JobSeekerParsedResumeResumeIdRoute,
}

const JobSeekerRouteWithChildren = JobSeekerRoute._addFileChildren(
  JobSeekerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AuthRoute: AuthRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  JobSeekerRoute: JobSeekerRouteWithChildren,
  RolesRoute: RolesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
